import { useState, useEffect, useCallback } from "react";

const STORAGE_KEY = "uilson_skills";

// Available tool categories that skills can use
export const TOOL_CATEGORIES = [
  {
    id: "gmail",
    label: "Gmail",
    icon: "📧",
    tools: ["gmail_search", "gmail_create_draft", "gmail_send_draft", "gmail_send_direct", "gmail_trash", "gmail_modify_labels", "gmail_list_labels", "gmail_get_attachments"],
    requiresAuth: "google",
  },
  {
    id: "calendar",
    label: "Googleカレンダー",
    icon: "📅",
    tools: ["calendar_list_events", "calendar_find_free_time", "calendar_check_conflicts", "calendar_create_event", "calendar_update_event", "calendar_delete_event"],
    requiresAuth: "google",
  },
  {
    id: "drive",
    label: "Google Drive",
    icon: "📁",
    tools: ["google_drive_search", "google_drive_list", "google_drive_get_content", "google_drive_create_doc"],
    requiresAuth: "google",
  },
  {
    id: "outlook",
    label: "Outlook",
    icon: "📨",
    tools: ["outlook_search_mail", "outlook_create_draft", "outlook_delete_mail", "outlook_move_mail", "outlook_mark_read", "outlook_flag_mail", "outlook_get_attachments", "outlook_list_folders"],
    requiresAuth: "microsoft",
  },
  {
    id: "outlook_cal",
    label: "Outlookカレンダー",
    icon: "🗓️",
    tools: ["outlook_list_events", "outlook_calendar_create", "outlook_calendar_update", "outlook_calendar_delete"],
    requiresAuth: "microsoft",
  },
  {
    id: "teams",
    label: "Teams",
    icon: "💬",
    tools: ["teams_list_chats", "teams_get_chat_messages", "teams_list_teams_channels", "teams_get_channel_messages"],
    requiresAuth: "microsoft",
  },
  {
    id: "sharepoint",
    label: "SharePoint",
    icon: "🏢",
    tools: ["sharepoint_search_sites", "sharepoint_list_files", "sharepoint_search_files", "sharepoint_get_file_content"],
    requiresAuth: "microsoft",
  },
  {
    id: "slack",
    label: "Slack",
    icon: "💼",
    tools: ["slack_search_users", "slack_read_dm", "slack_send_dm"],
    requiresAuth: "slack",
  },
  {
    id: "web",
    label: "Web検索",
    icon: "🔍",
    tools: ["web_search"],
    requiresAuth: null,
  },
];

// Preset approval gate options
export const APPROVAL_GATE_OPTIONS = [
  { id: "send_email", label: "メール送信前", description: "メールを送信する前に確認" },
  { id: "send_message", label: "メッセージ送信前", description: "Slack/Teamsメッセージ送信前に確認" },
  { id: "create_event", label: "予定作成前", description: "カレンダーに予定を作成する前に確認" },
  { id: "delete_anything", label: "削除操作前", description: "メール・予定・ファイルを削除する前に確認" },
  { id: "create_document", label: "ドキュメント作成前", description: "Google Docsなど作成する前に確認" },
  { id: "final_output", label: "最終結果の提示時", description: "最終結果をユーザーに見せて確認" },
];

function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export default function useSkills() {
  const [skills, setSkills] = useState([]);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) setSkills(JSON.parse(stored));
    } catch (e) {
      console.warn("Failed to load skills:", e);
    }
  }, []);

  const persist = useCallback((updated) => {
    setSkills(updated);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn("Failed to save skills:", e);
    }
  }, []);

  const createSkill = useCallback((data) => {
    const skill = {
      id: generateId(),
      name: data.name || "",
      goal: data.goal || "",
      toolCategories: data.toolCategories || [],
      constraints: data.constraints || [],
      approvalGates: data.approvalGates || [],
      context: data.context || "",
      // Generated by AI
      orchestration: data.orchestration || "",
      triggers: data.triggers || [],
      // Meta
      status: "learning",
      usageCount: 0,
      createdAt: new Date().toISOString(),
      lastUsed: null,
      step: 1,
    };
    const updated = [...skills, skill];
    persist(updated);
    return skill;
  }, [skills, persist]);

  const updateSkill = useCallback((id, changes) => {
    const updated = skills.map((s) => s.id === id ? { ...s, ...changes } : s);
    persist(updated);
    return updated.find((s) => s.id === id);
  }, [skills, persist]);

  const deleteSkill = useCallback((id) => {
    persist(skills.filter((s) => s.id !== id));
  }, [skills, persist]);

  const finalizeSkill = useCallback((id, orchestration, triggers) => {
    updateSkill(id, {
      orchestration,
      triggers: triggers || [],
      status: "active",
      step: 5,
    });
  }, [updateSkill]);

  const toggleSkill = useCallback((id) => {
    const skill = skills.find((s) => s.id === id);
    if (!skill) return;
    updateSkill(id, { status: skill.status === "active" ? "paused" : "active" });
  }, [skills, updateSkill]);

  // Generate the orchestration prompt for active skills
  const getActiveSkillsPrompt = useCallback(() => {
    const active = skills.filter((s) => s.status === "active" && s.orchestration);
    if (active.length === 0) return "";

    let prompt = "\n\n## ACTIVE SKILL ORCHESTRATIONS (autonomous execution blueprints):\n";
    prompt += "When user's request matches a skill's triggers/goal, follow the orchestration plan autonomously.\n";
    prompt += "Use the Plan→Execute→Observe loop: analyze the goal, plan tool calls, execute them, observe results, adjust plan if needed.\n";
    prompt += "ALWAYS respect approval gates — pause and ask the user before taking gated actions.\n\n";

    active.forEach((s) => {
      prompt += `### SKILL: ${s.name}\n`;
      prompt += `**GOAL**: ${s.goal}\n`;
      prompt += `**TRIGGERS**: ${s.triggers.join(", ") || "auto-detect from goal"}\n`;
      prompt += `**ALLOWED TOOLS**: ${s.toolCategories.map(tc => {
        const cat = TOOL_CATEGORIES.find(c => c.id === tc);
        return cat ? cat.tools.join(", ") : tc;
      }).join(", ")}\n`;
      if (s.constraints.length > 0) {
        prompt += `**CONSTRAINTS (MUST follow)**:\n${s.constraints.map(c => "- " + c).join("\n")}\n`;
      }
      if (s.approvalGates.length > 0) {
        const gateLabels = s.approvalGates.map(gId => {
          const gate = APPROVAL_GATE_OPTIONS.find(g => g.id === gId);
          return gate ? gate.label : gId;
        });
        prompt += `**APPROVAL GATES (MUST pause and confirm with user)**:\n${gateLabels.map(g => "- ⚠️ " + g).join("\n")}\n`;
      }
      if (s.context) {
        prompt += `**CONTEXT**: ${s.context}\n`;
      }
      prompt += `**ORCHESTRATION PLAN**:\n${s.orchestration}\n\n`;
    });

    return prompt;
  }, [skills]);

  return {
    skills,
    activeSkills: skills.filter((s) => s.status === "active"),
    learningSkills: skills.filter((s) => s.status === "learning"),
    pausedSkills: skills.filter((s) => s.status === "paused"),
    createSkill, updateSkill, deleteSkill,
    finalizeSkill, toggleSkill, getActiveSkillsPrompt,
  };
}
