import { useState, useEffect, useCallback } from "react";

const STORAGE_KEY = "uilson_skills";

// Action permissions: services where the AI can WRITE/SEND/CREATE/DELETE
// Reading/searching is ALWAYS allowed on all connected services
export const ACTION_PERMISSIONS = [
  {
    id: "gmail_send",
    label: "Gmailで送信",
    icon: "📧",
    description: "メールの送信・ドラフト作成",
    actions: ["gmail_create_draft", "gmail_send_draft", "gmail_send_direct"],
    requiresAuth: "google",
  },
  {
    id: "gmail_manage",
    label: "Gmailを整理",
    icon: "🗂️",
    description: "メールの削除・ラベル変更・既読/未読",
    actions: ["gmail_trash", "gmail_modify_labels"],
    requiresAuth: "google",
  },
  {
    id: "calendar_write",
    label: "Google予定を操作",
    icon: "📅",
    description: "予定の作成・変更・削除",
    actions: ["calendar_create_event", "calendar_update_event", "calendar_delete_event"],
    requiresAuth: "google",
  },
  {
    id: "drive_write",
    label: "Driveにドキュメント作成",
    icon: "📝",
    description: "Google Docsの新規作成",
    actions: ["google_drive_create_doc"],
    requiresAuth: "google",
  },
  {
    id: "outlook_send",
    label: "Outlookで送信",
    icon: "📨",
    description: "メールの送信・ドラフト作成",
    actions: ["outlook_create_draft"],
    requiresAuth: "microsoft",
  },
  {
    id: "outlook_manage",
    label: "Outlookを整理",
    icon: "📋",
    description: "メールの移動・削除・フラグ・既読",
    actions: ["outlook_delete_mail", "outlook_move_mail", "outlook_mark_read", "outlook_flag_mail"],
    requiresAuth: "microsoft",
  },
  {
    id: "outlook_cal_write",
    label: "Outlook予定を操作",
    icon: "🗓️",
    description: "Outlook予定の作成・変更・削除",
    actions: ["outlook_calendar_create", "outlook_calendar_update", "outlook_calendar_delete"],
    requiresAuth: "microsoft",
  },
  {
    id: "slack_send",
    label: "SlackでDM送信",
    icon: "💬",
    description: "Slackでダイレクトメッセージを送信",
    actions: ["slack_send_dm"],
    requiresAuth: "slack",
  },
];

// Preset approval gate options
export const APPROVAL_GATE_OPTIONS = [
  { id: "send_email", label: "メール送信前", description: "メールを送信する前に確認" },
  { id: "send_message", label: "メッセージ送信前", description: "Slack/Teamsメッセージ送信前に確認" },
  { id: "create_event", label: "予定作成前", description: "カレンダーに予定を作成する前に確認" },
  { id: "delete_anything", label: "削除操作前", description: "メール・予定・ファイルを削除する前に確認" },
  { id: "create_document", label: "ドキュメント作成前", description: "Google Docsなど作成する前に確認" },
  { id: "final_output", label: "最終結果の提示時", description: "最終結果をユーザーに見せて確認" },
];

function generateId() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 8);
}

export default function useSkills() {
  const [skills, setSkills] = useState([]);

  useEffect(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) setSkills(JSON.parse(stored));
    } catch (e) {
      console.warn("Failed to load skills:", e);
    }
  }, []);

  const persist = useCallback((updated) => {
    setSkills(updated);
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(updated));
    } catch (e) {
      console.warn("Failed to save skills:", e);
    }
  }, []);

  const createSkill = useCallback((data) => {
    const skill = {
      id: generateId(),
      name: data.name || "",
      goal: data.goal || "",
      actionPermissions: data.actionPermissions || [],
      constraints: data.constraints || [],
      approvalGates: data.approvalGates || [],
      context: data.context || "",
      // Generated by AI
      orchestration: data.orchestration || "",
      triggers: data.triggers || [],
      // Meta
      status: "learning",
      usageCount: 0,
      createdAt: new Date().toISOString(),
      lastUsed: null,
      step: 1,
    };
    const updated = [...skills, skill];
    persist(updated);
    return skill;
  }, [skills, persist]);

  const updateSkill = useCallback((id, changes) => {
    const updated = skills.map((s) => s.id === id ? { ...s, ...changes } : s);
    persist(updated);
    return updated.find((s) => s.id === id);
  }, [skills, persist]);

  const deleteSkill = useCallback((id) => {
    persist(skills.filter((s) => s.id !== id));
  }, [skills, persist]);

  const finalizeSkill = useCallback((id, orchestration, triggers) => {
    updateSkill(id, {
      orchestration,
      triggers: triggers || [],
      status: "active",
      step: 5,
    });
  }, [updateSkill]);

  const toggleSkill = useCallback((id) => {
    const skill = skills.find((s) => s.id === id);
    if (!skill) return;
    updateSkill(id, { status: skill.status === "active" ? "paused" : "active" });
  }, [skills, updateSkill]);

  // Generate the orchestration prompt for active skills
  const getActiveSkillsPrompt = useCallback(() => {
    const active = skills.filter((s) => s.status === "active" && s.orchestration);
    if (active.length === 0) return "";

    let prompt = "\n\n## ACTIVE SKILL ORCHESTRATIONS (autonomous execution blueprints):\n";
    prompt += "When user's request matches a skill's triggers/goal, follow the orchestration plan autonomously.\n";
    prompt += "Use the Plan→Execute→Observe loop: analyze the goal, plan tool calls, execute them, observe results, adjust plan if needed.\n";
    prompt += "IMPORTANT: You can ALWAYS use ALL read/search tools (gmail_search, calendar_list_events, web_search, weather_forecast, google_drive_search, outlook_search_mail, slack_read_dm, etc.) regardless of skill permissions. Permissions only restrict WRITE actions.\n";
    prompt += "ALWAYS respect approval gates — pause and ask the user before taking gated actions.\n\n";

    active.forEach((s) => {
      prompt += `### SKILL: ${s.name}\n`;
      prompt += `**GOAL**: ${s.goal}\n`;
      prompt += `**TRIGGERS**: ${s.triggers.join(", ") || "auto-detect from goal"}\n`;
      // Permitted actions (write/send/create/delete)
      const permittedActions = (s.actionPermissions || []).map(apId => {
        const perm = ACTION_PERMISSIONS.find(p => p.id === apId);
        return perm ? `${perm.label} (${perm.actions.join(", ")})` : apId;
      });
      if (permittedActions.length > 0) {
        prompt += `**PERMITTED ACTIONS (write/send/create/delete)**:\n${permittedActions.map(a => "- ✅ " + a).join("\n")}\n`;
      } else {
        prompt += `**PERMITTED ACTIONS**: READ-ONLY (no write/send/create/delete actions allowed)\n`;
      }
      prompt += `**INFORMATION GATHERING**: All search/read tools are available — use web_search, weather_forecast, gmail_search, calendar_list_events, google_drive_search, etc. freely to gather information needed for the goal.\n`;
      if (s.constraints.length > 0) {
        prompt += `**CONSTRAINTS (MUST follow)**:\n${s.constraints.map(c => "- 🚫 " + c).join("\n")}\n`;
      }
      if (s.approvalGates.length > 0) {
        const gateLabels = s.approvalGates.map(gId => {
          const gate = APPROVAL_GATE_OPTIONS.find(g => g.id === gId);
          return gate ? gate.label : gId;
        });
        prompt += `**APPROVAL GATES (MUST pause and confirm with user)**:\n${gateLabels.map(g => "- ⚠️ " + g).join("\n")}\n`;
      }
      if (s.context) {
        prompt += `**CONTEXT**: ${s.context}\n`;
      }
      prompt += `**ORCHESTRATION PLAN**:\n${s.orchestration}\n\n`;
    });

    return prompt;
  }, [skills]);

  return {
    skills,
    activeSkills: skills.filter((s) => s.status === "active"),
    learningSkills: skills.filter((s) => s.status === "learning"),
    pausedSkills: skills.filter((s) => s.status === "paused"),
    createSkill, updateSkill, deleteSkill,
    finalizeSkill, toggleSkill, getActiveSkillsPrompt,
  };
}
